name: hackathon_project
description: A new Flutter project for hackathon.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.2
  flutter_lints: ^1.0.0
  toast: ^0.1.5
  fluttertoast: ^8.0.8
  particles_flutter: ^0.1.4
  flutter_spinkit: ^5.1.0
  cupertino_icons: ^1.0.2
  firebase_storage: ^8.0.3
  firebase_core: ^1.0.2
  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.5
  jitsi_meet: ^4.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
flutter_icons:
  image_path: "assets/teaching.png"
  android: true
  ios: true
flutter:

  uses-material-design: true
  assets:
    - assets/iconBg.png
    - assets/teaching.png
    - assets/english.png
    - assets/french.png
    - assets/math.png
    - assets/science.png
    - assets/social-science.png
